language: generic
sudo: required
os:
- linux
- osx
services:
- docker
branches:
  only:
  - master
env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36
  global:
    secure: BTt0VMolkwMYxgPQZpwSFArYJ5GReneJws7s/P5w3RZ89trj2rRtVecUTYUIqg1qCLrltutAs/xfumYQAEgR/Lj8aC2irSm5Qo/xvcVbnozU56QsZeoNMK7vFRbF9HgPRvo8HaYmbI8dn+Av+pJhUMmsxEt+USa8TZPzVruqLhD1x+LooDnCd+TfPMt9bZtr6f3nQRcPzMV+WDyY3KMfyWxM+MvFZULzl1HpnLFJsibReyF8dvjdZwXSzaUno1saoOdY+ie8ZX3JLmki3qnr2mlhgPKySugi606LuysLPx26vDeYYd9HcHEDFB4IclOVAv46vok370SLY3S8Qa0pHcZ1Gkc9mzxTh8uW9MPFPAC7o7Oe0bcoPcKnXoIQQ9ZOvdxrjii0T5g0SG2Gqpg6wQgEP8OIVw2curXOTO/E90QuyfrWLhctRRNM0drokU9TZXzvfKwIPCOiy+C4SCivL42h89IYbB8zYkcZEFWBh3MLzq+9ySymIMeDhqLBczrf5xL/ABpO+NerQNElWDkSTE9zAtBohun7UJLIRX23sBHikbkeVWPKZtsKTDgeoSoK86VoGZFtwmcpp8VIvD4Xt4JsRSazxD0eapd1c5P+47aK2t0G6QO3LW5bMklYGCoz/vF+vHhSSnwe44uhiUXif8EBj4w6tl/NtvhGHdgvuzU=
install:
- |
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-$(case $TRAVIS_OS_NAME in (linux) echo Linux;; (osx) echo MacOSX;;esac)-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo "Configuring conda."
  source $HOME/miniconda3/bin/activate root
- |
  echo "Installing dependencies."
  conda install -y conda-build anaconda-client flake8
  flake8 .  # Fail fast on syntax errors
  # python.app conflicts with postgresadapter's installation
  # conda remove -y python.app
script:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      conda build -c "https://conda.anaconda.org/t/$ANACONDA_TOKEN/intake" --python "${CONDA_PY:0:1}.${CONDA_PY:1:2}" ./conda
  else
      # Workaround for Travis-CI bug #2: https://github.com/travis-ci/travis-ci/issues/7773
      conda build -c "https://conda.anaconda.org/t/$ANACONDA_TOKEN/intake" --no-test --python "${CONDA_PY:0:1}.${CONDA_PY:1:2}" ./conda
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then anaconda -t ${ANACONDA_TOKEN}
  upload --force `conda build -c intake/label/main --output ./conda`; else echo "skipping upload"; fi
notifications:
  email: false
  on_success: change
  on_failure: always
