package:
   name: intake-postgres
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - intake>=0.2
    - postgresadapter

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
    - psycopg2
    - sqlalchemy
    - postgresql
    - shapely
  commands:
    - py.test --verbose --cov=intake_postgres tests

about:
  home: https://github.com/ContinuumIO/intake-postgres
  license: BSD
  license_file: LICENSE
  summary: |
    PostgreSQL plugin for Intake
