package:
   name: intake_postgres
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - jinja2
    - postgresql
  run:
    - intake
    - python
    - psycopg2
    - sqlalchemy

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --cov=.

about:
  home: https://github.com/ContinuumIO/intake-postgres
  license: BSD
  license_file: LICENSE
  summary: |
    PostgreSQL plugin for Intake
